# Databricks Apps configuration
# See: https://docs.databricks.com/aws/en/dev-tools/databricks-apps/app-runtime
#
# Database Resource Setup:
# 1. In Databricks Apps UI, click "Add resource" when configuring the app
# 2. Select "Database" as the resource type
# 3. Choose your Lakebase instance and database
# 4. The PG* environment variables will be set automatically

command: [
  "uvicorn", "server.app:app", "--host", "0.0.0.0"
]
env:
  - name: ENV
    value: production
  # Databricks workspace URL (needed for SDK to authenticate with service principal)
  - name: DATABRICKS_HOST
    value: "https://fe-vm-industry-solutions-buildathon.cloud.databricks.com"
  # DBSQL configuration for financial data and user profiles
  - name: DBSQL_SCHEMA
    value: "personal_finance_app.dev"  # TODO: Replace with your catalog.schema
  - name: DATABRICKS_SERVER_HOSTNAME
    value: "fe-vm-industry-solutions-buildathon.cloud.databricks.com"
  - name: DATABRICKS_HTTP_PATH
    value: "/sql/1.0/warehouses/your_warehouse_id"  # TODO: Replace with your warehouse path
  # For DBSQL auth - in Databricks Apps, the service principal credentials are auto-injected
  # (DATABRICKS_CLIENT_ID and DATABRICKS_CLIENT_SECRET)
  # Do NOT set DATABRICKS_TOKEN here - it will conflict with service principal auth
  # News API for financial news feed (get key from https://newsapi.org)
  - name: NEWSAPI_KEY
    value: "your_newsapi_key"  # TODO: Replace with your API key
  # MLflow experiment for tracing (use NAME or ID, not both)
  - name: MLFLOW_EXPERIMENT_NAME
    value: "/Users/your.email@company.com/personal-finance-app"  # TODO: Replace with your experiment path
  # - name: MLFLOW_EXPERIMENT_ID
  #   value: "123456789"  # Alternative: use numeric ID if experiment already exists
  # MCP connections for external tools (optional - overrides config/app.json)
  # Comma-separated list of MCP connection names configured in Databricks
  - name: MCP_CONNECTIONS
    value: "your-search-mcp"  # TODO: Replace with your MCP connection name
  # Lakebase instance name - set this to your instance name for OAuth token generation
  # The database resource provides PGHOST, PGUSER, PGDATABASE, PGPORT, PGSSLMODE
  # - name: LAKEBASE_INSTANCE_NAME
  #   valueFrom: database