#!/bin/bash

# Setup script - Configure environment and install dependencies

set -e

ENV_FILE=".env.local"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔧 Environment Setup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Check if .env.local exists
if [ -f "$ENV_FILE" ]; then
    echo "⚠️  .env.local already exists"
    echo ""
    read -p "Overwrite? (y/n): " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Skipping environment configuration..."
        echo ""
    else
        rm "$ENV_FILE"
    fi
fi

# Configure environment if .env.local doesn't exist or was deleted
if [ ! -f "$ENV_FILE" ]; then
    echo "📝 Required Configuration (for local development):"
    echo ""
    read -p "DATABRICKS_HOST (e.g., https://adb-xxx.azuredatabricks.net): " DATABRICKS_HOST
    read -p "DATABRICKS_TOKEN (your personal access token): " DATABRICKS_TOKEN

    echo ""
    echo "📝 Optional Configuration (for deployment to Databricks Apps):"
    echo ""
    read -p "DATABRICKS_APP_NAME (press Enter to skip): " DATABRICKS_APP_NAME
    read -p "WORKSPACE_SOURCE_PATH (e.g., /Workspace/Users/you@company.com/app-name, press Enter to skip): " WORKSPACE_SOURCE_PATH

    # Create .env.local
    cat > "$ENV_FILE" << EOF
# Generated by setup.sh on $(date)
# Required for local development
DATABRICKS_HOST=$DATABRICKS_HOST
DATABRICKS_TOKEN=$DATABRICKS_TOKEN
EOF

    # Add deployment config if provided
    if [ ! -z "$DATABRICKS_APP_NAME" ]; then
        echo "
# Deployment configuration
DATABRICKS_APP_NAME=$DATABRICKS_APP_NAME" >> "$ENV_FILE"
    fi

    if [ ! -z "$WORKSPACE_SOURCE_PATH" ]; then
        echo "WORKSPACE_SOURCE_PATH=$WORKSPACE_SOURCE_PATH" >> "$ENV_FILE"
    fi

    echo ""
    echo "✅ .env.local created"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📦 Installing Dependencies"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Install Python dependencies with uv
echo "🐍 Installing Python dependencies..."
if ! command -v uv &> /dev/null; then
    echo "❌ uv not found"
    read -p "Install uv now? (Y/n): " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Nn]$ ]]; then
        curl -LsSf https://astral.sh/uv/install.sh | sh
        export PATH="$HOME/.cargo/bin:$PATH"
    else
        echo "⚠️  Install uv manually: curl -LsSf https://astral.sh/uv/install.sh | sh"
        exit 1
    fi
fi

# uv sync creates .venv/ and installs all dependencies from pyproject.toml
uv sync
echo "✅ Python dependencies installed (.venv/ created)"
echo ""

# Install frontend dependencies with bun
echo "📱 Installing frontend dependencies..."
if ! command -v bun &> /dev/null; then
    echo "❌ bun not found"
    read -p "Install bun now? (Y/n): " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Nn]$ ]]; then
        curl -fsSL https://bun.sh/install | bash
        export PATH="$HOME/.bun/bin:$PATH"
    else
        echo "⚠️  Install bun manually: curl -fsSL https://bun.sh/install | bash"
        exit 1
    fi
fi

cd client && bun install && cd ..
echo "✅ Frontend dependencies installed"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 Setup Complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Next steps:"
echo "  1. Run: ./scripts/start_dev.sh"
echo "  2. Open: http://localhost:3000"
echo ""
