#!/bin/bash

# Setup script - Configure environment and install dependencies

set -e

ENV_FILE=".env.local"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔧 Environment Setup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Check if .env.local exists
if [ -f "$ENV_FILE" ]; then
    echo "⚠️  .env.local already exists"
    echo ""
    read -p "Overwrite? (y/n): " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Skipping environment configuration..."
        echo ""
    else
        rm "$ENV_FILE"
    fi
fi

# Configure environment if .env.local doesn't exist or was deleted
if [ ! -f "$ENV_FILE" ]; then
    echo "📝 Required Configuration (for local development):"
    echo ""
    read -p "DATABRICKS_HOST (e.g., https://your-workspace.cloud.databricks.com): " DATABRICKS_HOST
    read -p "DATABRICKS_TOKEN (your personal access token): " DATABRICKS_TOKEN
    read -p "DATABRICKS_CONFIG_PROFILE (CLI profile name, press Enter for 'DEFAULT'): " DATABRICKS_CONFIG_PROFILE
    DATABRICKS_CONFIG_PROFILE=${DATABRICKS_CONFIG_PROFILE:-DEFAULT}

    echo ""
    echo "📝 Databricks SQL Configuration (for real financial data):"
    echo "   Leave blank to use sample data instead."
    echo ""
    read -p "DBSQL_SCHEMA (e.g., catalog.schema): " DBSQL_SCHEMA
    read -p "DATABRICKS_SERVER_HOSTNAME (e.g., your-workspace.cloud.databricks.com): " DATABRICKS_SERVER_HOSTNAME
    read -p "DATABRICKS_HTTP_PATH (e.g., /sql/1.0/warehouses/abc123): " DATABRICKS_HTTP_PATH

    echo ""
    echo "📝 Deployment Configuration (for ./scripts/deploy.sh):"
    echo ""
    read -p "DATABRICKS_APP_NAME (press Enter to skip): " DATABRICKS_APP_NAME
    read -p "WORKSPACE_SOURCE_PATH (e.g., /Workspace/Users/you@company.com/app-name, press Enter to skip): " WORKSPACE_SOURCE_PATH

    # Create .env.local
    cat > "$ENV_FILE" << EOF
# Generated by setup.sh on $(date)

# Databricks Workspace (Required)
DATABRICKS_HOST=$DATABRICKS_HOST
DATABRICKS_TOKEN=$DATABRICKS_TOKEN
DATABRICKS_CONFIG_PROFILE=$DATABRICKS_CONFIG_PROFILE
EOF

    # Add DBSQL config if provided
    if [ ! -z "$DBSQL_SCHEMA" ]; then
        cat >> "$ENV_FILE" << EOF

# Databricks SQL (for real financial data)
DBSQL_SCHEMA=$DBSQL_SCHEMA
DATABRICKS_SERVER_HOSTNAME=$DATABRICKS_SERVER_HOSTNAME
DATABRICKS_HTTP_PATH=$DATABRICKS_HTTP_PATH
EOF
    fi

    # Add deployment config if provided
    if [ ! -z "$DATABRICKS_APP_NAME" ]; then
        cat >> "$ENV_FILE" << EOF

# Deployment configuration
DATABRICKS_APP_NAME=$DATABRICKS_APP_NAME
EOF
    fi

    if [ ! -z "$WORKSPACE_SOURCE_PATH" ]; then
        echo "WORKSPACE_SOURCE_PATH=$WORKSPACE_SOURCE_PATH" >> "$ENV_FILE"
    fi

    echo ""
    echo "✅ .env.local created"
    echo ""
    echo "💡 Tip: Edit .env.local to add optional settings like NEWSAPI_KEY"
    echo "   See .env.template for all available options."
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📦 Installing Dependencies"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Install Python dependencies with uv
echo "🐍 Installing Python dependencies..."
if ! command -v uv &> /dev/null; then
    echo "❌ uv not found"
    read -p "Install uv now? (Y/n): " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Nn]$ ]]; then
        curl -LsSf https://astral.sh/uv/install.sh | sh
        export PATH="$HOME/.cargo/bin:$PATH"
    else
        echo "⚠️  Install uv manually: curl -LsSf https://astral.sh/uv/install.sh | sh"
        exit 1
    fi
fi

# uv sync creates .venv/ and installs all dependencies from pyproject.toml
uv sync
echo "✅ Python dependencies installed (.venv/ created)"
echo ""

# Install frontend dependencies with bun
echo "📱 Installing frontend dependencies..."
if ! command -v bun &> /dev/null; then
    echo "❌ bun not found"
    read -p "Install bun now? (Y/n): " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Nn]$ ]]; then
        curl -fsSL https://bun.sh/install | bash
        export PATH="$HOME/.bun/bin:$PATH"
    else
        echo "⚠️  Install bun manually: curl -fsSL https://bun.sh/install | bash"
        exit 1
    fi
fi

cd client && bun install && cd ..
echo "✅ Frontend dependencies installed"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 Setup Complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Next steps:"
echo "  1. Run: ./scripts/start_dev.sh"
echo "  2. Open: http://localhost:3000"
echo ""
